# spritesheet: name_of_the_spritesheet
#   {type_of_the_sprite}: id_of_the_sprite
#     anim: id_of_the_animation
#       rect_x: ... (optional)
#       rect_y: ... (optional)
#       rect_width: ... (optional)
#       rect_height: ... (optional)
#       nb_anim: ... (optional)
#       next_anim: ... (optional)
#       ...
#     ...
#
# {type_of_the_sprite} is : spaceship, monster
#
# Example:
#
#spritesheet: r-typesheet42.gif
# spaceship: 0
#  anim: 0
#   rect_x: 1
#   rect_y: 1
#   rect_width: 32
#   rect_height: 17
#   nb_anim: 5
#   next_anim: 1
#  anim: 1
#   rect_x: 2
#   rect_y: 2
#   rect_width: 42
#   rect_height: 27
#   nb_anim: 15
#   next_anim: 0
spritesheet: background.jpg
 background: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 1337
   rect_height: 720

spritesheet: logo.png
 background: 1
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 1085
   rect_height: 193

spritesheet: button.png
 button: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 300
   rect_height: 110

spritesheet: button.png
 room: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 300
   rect_height: 110

spritesheet: spaceships.gif
 spaceship: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 132
   rect_height: 72
   nb_anim: 4

spritesheet: nsm
 monster: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 72
   rect_height: 72

spritesheet: create_private_game_btn.png
 button: 1
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 177
   rect_height: 75

spritesheet: create_public_game_btn.png
 button: 2
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 192
   rect_height: 75

spritesheet: exit_btn.png
 button: 3
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 378
   rect_height: 54

spritesheet: htp_btn.png
 button: 4
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 378
   rect_height: 54

spritesheet: joingame_btn.png
 button: 5
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 378
   rect_height: 53

spritesheet: settings_btn.png
 button: 6
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 378
   rect_height: 53