# spritesheet: name_of_the_spritesheet
#   {type_of_the_sprite}: id_of_the_sprite
#     anim: id_of_the_animation
#       rect_x: ... (not optional)
#       rect_y: ... (not optional)
#       rect_width: ... (not optional)
#       rect_height: ... (not optional)
#       nb_anim: ... (optional)
#       speed_anim: ... (optional)
#       next_anim: ... (optional)
#       ...
#     ...
#
# {type_of_the_sprite} is : spaceship, monster
#
# Example:
#
#spritesheet: r-typesheet42.gif
# spaceship: 0
#  anim: 0
#   rect_x: 1
#   rect_y: 1
#   rect_width: 32
#   rect_height: 17
#   nb_anim: 5
#   speed_anim: 2
#   next_anim: 1
#  anim: 1
#   rect_x: 2
#   rect_y: 2
#   rect_width: 42
#   rect_height: 27
#   nb_anim: 15
#   next_anim: 0

spritesheet: nsm
 monster: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 72
   rect_height: 72

# ------------------------BACKGROUNDS------------------------
spritesheet: backgrounds/background.jpg
 background: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 1327
   rect_height: 720
spritesheet: backgrounds/background.jpg
 parallax: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 1327
   rect_height: 720

spritesheet: backgrounds/logo.png
 background: 1
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 1085
   rect_height: 193

spritesheet: backgrounds/black_filter.png
 background: 2
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 1280
   rect_height: 720

spritesheet: backgrounds/logo_btn_background.png
 background: 3
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 1280
   rect_height: 720

spritesheet: backgrounds/settings_box.png
 background: 4
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 761
   rect_height: 414

spritesheet: backgrounds/type_pseudo_box.png
 background: 5
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 866
   rect_height: 281

spritesheet: backgrounds/setting_sound_bar.png
 background: 6
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 611
   rect_height: 74

spritesheet: backgrounds/setting_enter_name_bar.png
 background: 7
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 485
   rect_height: 74

spritesheet: backgrounds/type_pseudo_bar.png
 background: 8
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 701
   rect_height: 85

spritesheet: backgrounds/how_to_play.png
 background: 9
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 828
   rect_height: 621

spritesheet: backgrounds/logo_menu_join.png
 background: 10
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 419
   rect_height: 132

spritesheet: backgrounds/private_room_logo.png
 background: 11
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 214
   rect_height: 79

spritesheet: backgrounds/bg_private_room_zone.png
 background: 12
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 320
   rect_height: 231

spritesheet: backgrounds/public_mainframe.png
 background: 13
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 679
   rect_height: 495

spritesheet: backgrounds/lobby_logo_top.png
 background: 14
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 761
   rect_height: 84

spritesheet: backgrounds/lobby_mode_frame.png
 background: 15
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 224
   rect_height: 75

spritesheet: backgrounds/lobby_player_frame.png
 background: 16
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 353
   rect_height: 518

spritesheet: backgrounds/planet_level_info.png
 background: 17
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 360
   rect_height: 198

spritesheet: planets/sun.png
 background: 18
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 244
   rect_height: 244
   nb_anim: 29

spritesheet: backgrounds/locked_achievement.png
 background: 19
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 860
   rect_height: 134

spritesheet: backgrounds/achievement.png
 background: 20
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 860
   rect_height: 134

# ------------------------BUTTONS------------------------
spritesheet: buttons/create_private_game_btn.png
 button: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 177
   rect_height: 75
   nb_anim: 3

spritesheet: buttons/create_public_game_btn.png
 button: 1
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 191
   rect_height: 75
   nb_anim: 3

spritesheet: buttons/exit_btn.png
 button: 2
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 378
   rect_height: 54
   nb_anim: 3

spritesheet: buttons/htp_btn.png
 button: 3
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 378
   rect_height: 54
   nb_anim: 3

spritesheet: buttons/joingame_btn.png
 button: 4
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 378
   rect_height: 53
   nb_anim: 3

spritesheet: buttons/settings_btn.png
 button: 5
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 378
   rect_height: 53
   nb_anim: 3

spritesheet: buttons/back_button.png
 button: 6
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 100
   rect_height: 79
   nb_anim: 3

spritesheet: buttons/private_join_btn.png
 button: 7
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 177
   rect_height: 78

spritesheet: buttons/versus_btn.png
 button: 8
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 303
   rect_height: 104
   nb_anim: 3

spritesheet: buttons/coop_btn.png
 button: 9
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 215
   rect_height: 89
   nb_anim: 3

spritesheet: buttons/achievement_btn.png
 button: 10
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 99
   rect_height: 96
   nb_anim: 3

spritesheet: buttons/confirm_btn.png
 button: 11
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 100
   rect_height: 79
   nb_anim: 3

spritesheet: buttons/lobby_start_button.png
 button: 12
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 348
   rect_height: 83
   nb_anim: 3

spritesheet: buttons/arrow1.png
 button: 13
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 45
   rect_height: 45

spritesheet: buttons/arrow2.png
 button: 14
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 45
   rect_height: 45

spritesheet: buttons/refresh_btn.png
 button: 15
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 88
   rect_height: 89

spritesheet: planets/black_hole.png
 button: 16
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 218
   rect_height: 86
   nb_anim: 29

spritesheet: planets/rock_planet.png
 button: 17
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 218
   rect_height: 146
   nb_anim: 29

spritesheet: planets/fire_planet.png
 button: 18
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 129
   rect_height: 129
   nb_anim: 29

spritesheet: planets/ice_planet.png
 button: 19
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 129
   rect_height: 129
   nb_anim: 29

spritesheet: planets/forest_planet.png
 button: 20
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 129
   rect_height: 129
   nb_anim: 29

# ------------------------ROOMS------------------------
spritesheet: rooms/public_game_select_room.png
 room: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 655
   rect_height: 115

# ------------------------ROOMMODES------------------------
spritesheet: roommodes/coop_logo.png
 roommode: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 127
   rect_height: 53

spritesheet: roommodes/versus_logo.png
 roommode: 1
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 147
   rect_height: 53

# ------------------------TEXTBOXS------------------------
spritesheet: textboxs/textbox_room_id.png
 textbox: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 223
   rect_height: 68

# ------------------------SPACESHIPS------------------------
spritesheet: spaceships/spaceship-1.png
 spaceship: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 137
   rect_height: 97
   nb_anim: 5
   speed_anim: 15

spritesheet: spaceships/spaceship-2.png
 spaceship: 1
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 137
   rect_height: 97
   nb_anim: 5
   speed_anim: 15

spritesheet: spaceships/spaceship-3.png
 spaceship: 2
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 137
   rect_height: 97
   nb_anim: 5
   speed_anim: 15

spritesheet: spaceships/spaceship-4.png
 spaceship: 3
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 137
   rect_height: 97
   nb_anim: 5
   speed_anim: 15

# ------------------------SHOT------------------------
#CLASSIC
spritesheet: filsdechienne
 shot: 0
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 100
   rect_height: 50

#BEAM
spritesheet: filsdechienne2
 shot: 1
  anim: 0
   rect_x: 0
   rect_y: 0
   rect_width: 1280
   rect_height: 15
