name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create build
      run: mkdir build && cd build

    - name: Install Conan & Python
      run: |
        sudo apt-get upgrade python3
        sudo pip install conan
        conan profile update settings.compiler.libcxx=libstdc++11
        conan install . --build missing

    - name: Configure
      run: cmake .. -G 'Unix Makefiles' ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build

  windows_build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Create build
      run: mkdir build && cd build

    - name: Install Conan & Python
      run: |
        apt-get install -y python3
        pip install conan
        conan profile update settings.compiler.libcxx=libstdc++11
        conan install . --build missing

    - name: Configure
      run: cmake .. -G 'Visual Studio 17 2022' ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build