name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: bash
        run: pip install conan

      - name: Set and Update conan profile
        shell: bash
        run: |
          conan profile new default --detect
          echo [conf]\ntools.system.package_manager:sudo=True\ntools.system.package_manager:mode=install >> ~/.conan/profiles/default

      - name: build
        shell: bash
        run: |
          sudo apt-get install libX11-xcb-dev libfontenc-dev libXaw7-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXfixes-dev libXi-dev libXinerama-dev libXmu-dev libXmuu-dev libXpm-dev libXrandr-dev libXres-dev libXss-dev libXtst-dev libXv-dev libXvmc-dev libXxf86vm-dev libXcb-render-util0-dev libXcb-xkb-dev libXcb-icccm4-dev libXcb-image0-dev libXcb-keysyms1-dev libXcb-randr0-dev libXcb-shape0-dev libXcb-sync-dev libXcb-xfixes0-dev libXcb-xinerama0-dev libXcb-dri3-dev libXcb-util-dev libXcb-util0-dev;
          export CONAN_SYSREQUIRES_MODE="enabled"
          export CONAN_SYSREQUIRES_SUDO="1"
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-11 ${{ github.workspace }}
          cmake ${{ github.workspace }} -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build ${{ github.workspace }}/build