name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create build
      run: mkdir build && cd build

    - name: Install Conan
      run: |
        apt-get install libfontenc-devel
        apt-get install libXaw-devel
        apt-get install libXcomposite-devel
        apt-get install libXdmcp-devel
        apt-get install libXtst-devel
        apt-get install libxkbfile-devel
        apt-get install libXres-devel
        apt-get install libXScrnSaver-devel
        apt-get install libXvMC-devel
        apt-get install xorg-x11-xtrans-devel
        apt-get install xcb-util-wm-devel
        apt-get install xcb-util-keysyms-devel
        apt-get install xcb-util-renderutil-devel
        apt-get install libXdamage-devel
        apt-get install xcb-util-devel
        apt-get install xkeyboard-config-devel
        conan install . --build missing

    - name: Configure
      run: cmake .. -G 'Unix Makefiles' ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build

  windows_build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Create build
      run: mkdir build && cd build

    - name: Install Conan
      run: |
        apt-get install libfontenc-devel
        apt-get install libXaw-devel
        apt-get install libXcomposite-devel
        apt-get install libXdmcp-devel
        apt-get install libXtst-devel
        apt-get install libxkbfile-devel
        apt-get install libXres-devel
        apt-get install libXScrnSaver-devel
        apt-get install libXvMC-devel
        apt-get install xorg-x11-xtrans-devel
        apt-get install xcb-util-wm-devel
        apt-get install xcb-util-keysyms-devel
        apt-get install xcb-util-renderutil-devel
        apt-get install libXdamage-devel
        apt-get install xcb-util-devel
        apt-get install xkeyboard-config-devel
        conan install . --build missing

    - name: Configure
      run: cmake .. -G 'Visual Studio 17 2022' ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build