name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create build
      run: mkdir build && cd build

    - name: Install Conan
      run: |
        sudo pip install conan
        export CONAN_USER_HOME="/tmp/conan"
        export CONAN_SYSREQUIRES_MODE="enabled"
        conanexport CONAN_SYSREQUIRES_SUDO="1"
        conan remove --system-reqs "*" 
        conan install . -c tools.system.package_manager:mode=install

    - name: Configure
      run: cmake .. -G 'Unix Makefiles' ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build

  windows_build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Create build
      run: mkdir build && cd build

    - name: Install Conan
      run: |
        pip install conan
        $env:CONAN_USER_HOME="C:\conan"
        $env:CONAN_SYSREQUIRES_MODE="enabled"
        $env:CONAN_SYSREQUIRES_SUDO="1"
        conan remove --system-reqs "*" 
        conan install . --build missing

    - name: Configure
      run: cmake .. -G 'Visual Studio 17 2022' ${{ github.workspace }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build