name: Linux Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: bash
        run: |
          python --version
          sudo pip install conan
          sudo apt-get updatelibfontenc-devel libXaw-devel libXcomposite-devel libXdmcp-devel libXtst-devel libxkbfile-devel libXres-devel libXScrnSaver-devel libXvMC-devel xorg-x11-xtrans-devel xcb-util-wm-devel xcb-util-keysyms-devel xcb-util-renderutil-devel libXdamage-devel xcb-util-devel xkeyboard-config-devel

      - name: Set and Update conan profile
        shell: bash
        run: |
          conan profile new default --detect
          echo [conf]\ntools.system.package_manager:sudo=True\ntools.system.package_manager:mode=install >> ~/.conan/profiles/default
          mkdir build && cd build
          sudo apt-get remove libfontenc-devel libXaw-devel libXcomposite-devel libXdmcp-devel libXtst-devel libxkbfile-devel libXres-devel libXScrnSaver-devel libXvMC-devel xorg-x11-xtrans-devel xcb-util-wm-devel xcb-util-keysyms-devel xcb-util-renderutil-devel libXdamage-devel xcb-util-devel xkeyboard-config-devel
          sudo apt-get install libfontenc-devel libXaw-devel libXcomposite-devel libXdmcp-devel libXtst-devel libxkbfile-devel libXres-devel libXScrnSaver-devel libXvMC-devel xorg-x11-xtrans-devel xcb-util-wm-devel xcb-util-keysyms-devel xcb-util-renderutil-devel libXdamage-devel xcb-util-devel xkeyboard-config-devel
          conan install .. --build=missing

      - name: Build Test Linux
        shell: bash
        run: |
          export CONAN_SYSREQUIRES_MODE="enabled"
          export CONAN_SYSREQUIRES_SUDO="1"
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-11 ${{ github.workspace }}
          cmake ${{ github.workspace }} -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build ${{ github.workspace }}/build
