name: Linux Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  linux_build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: install-conan
        shell: bash
        run: |
          python --version
          sudo pip install conan

      - name: Set and Update conan profile
        shell: bash
        run: |
          conan profile new default --detect
          echo [conf]\ntools.system.package_manager:sudo=True\ntools.system.package_manager:mode=install >> ~/.conan/profiles/default
          mkdir build && cd build
          sudo apt-get install libx11-xcb-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libudev-dev libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libxcb-util-dev
          conan install .. --build=missing

      - name: Build Test Linux
        shell: bash
        run: |
          export CONAN_SYSREQUIRES_MODE="enabled"
          export CONAN_SYSREQUIRES_SUDO="1"
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-11 ${{ github.workspace }}
          cmake ${{ github.workspace }} -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build ${{ github.workspace }}/build